apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: henok2346/multi-worker
          env:
            - name: REDIS_HOST 
              value: redis-cluster-ip-service #this the name of the redis cluster ip service
            - name: REDIS_PORT
              value: '6379' # MUST BE THE SAME AS THE PORT DEFINED FOR THE REDIS CONTIANER